"""initial schema

Revision ID: 1e35ad531053
Revises: 
Create Date: 2026-07-19 13:45:37.874346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e35ad531053'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'domain',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('conversations', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('conversations', 'domain',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
