"""add_patient_profile_fields

Revision ID: 45f6853967af
Revises: 44a0af2fd2ab
Create Date: 2026-07-21 22:26:30.688998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f6853967af'
down_revision: Union[str, Sequence[str], None] = '44a0af2fd2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('patient_profiles', sa.Column('blood_group', sa.String(length=10), nullable=True))
    op.add_column('patient_profiles', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('patient_profiles', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('patient_profiles', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('patient_profiles', sa.Column('current_medications', sa.Text(), nullable=True))
    op.add_column('patient_profiles', sa.Column('medical_history', sa.Text(), nullable=True))
    op.add_column('patient_profiles', sa.Column('insurance_provider', sa.String(length=100), nullable=True))
    op.add_column('patient_profiles', sa.Column('insurance_policy_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'insurance_policy_number')
    op.drop_column('patient_profiles', 'insurance_provider')
    op.drop_column('patient_profiles', 'medical_history')
    op.drop_column('patient_profiles', 'current_medications')
    op.drop_column('patient_profiles', 'allergies')
    op.drop_column('patient_profiles', 'address')
    op.drop_column('patient_profiles', 'marital_status')
    op.drop_column('patient_profiles', 'blood_group')
    op.drop_column('patient_profiles', 'gender')
    # ### end Alembic commands ###
